name: "CI - Nix"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: "Nix build on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: [macos, ubuntu]
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      # - uses: cachix/cachix-action@v15
      #   with:
      #     name: gepetto
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L
